### ISSUE TITLE
Resizing Support in Caesium-clt

### ISSUE THREAD

**Issue by ImanMesgaran** [Lymphatus/caesium-clt#22]
Hi, is there any command that can be used to resize the image while compressing in command line tool?

**Comment by Lymphatus** [comment]
No at the moment. There're a couple of problems with this:
- For JPEGs, with lossless compression, you can downscale to a power of 2, otherwise you will lose quality. With lossy compression this is a bit different, as the image already is a bit different. The quality heavily depends on the downscale algorithm.
- PNG is lossless, so this does not apply.

I'm thinking of adding such a feature - since the desktop version already has it - but I just want to be sure the result will be good.

**Comment by Lymphatus** [comment]
### UPDATE
I've added an experimental resize option in the 0.12.0 branch. By adding the `-s` flag to command line arguments, you can specify a scaling factor to which the image will be resized.

The application accept a factor formatted in one of the following formats:
- Floating point number, like `.5` or `0.35`
- Fractions, like `3/4`
- Percentages, like `40%`

So, an example command would be like
`caesiumclt -q 80 -s .5 -o path/to/output path/to/input` (this will resize the image to half)

Note that this is an experimental feature and by now, you can only **downscale** an image.
You can try it in the [0.12.0 branch](https://github.com/Lymphatus/caesium-clt/tree/0.12.0)
