### ISSUE TITLE
How can I help this project out?

### ISSUE THREAD

**Issue by shimizurei** [Lymphatus/caesium-clt#34]
I'm not a coder (I can barely manipulate other's python scripts), but I would like to see this project succeed. It does what I want it to do pretty well (when it works) and there's no additional frills attached. How can I test things? Should I be printing the exif data of files that crash the program? How can I determine the root of an issue without knowing the language/how to code? I'm on Windows btw.

**Comment by Lymphatus** [comment]
I don't think it's because of the EXIF data attached, but I think it might be something related to the OS, because on Linux/OS X the program does its job pretty well and I didn't see any random crashes.

About your contribution: first of all, you're already doing a great job reporting me issues, which is huge. You can run tests on different sets of images, see what happens and reporting me the result. Every detail can help me finding the issue.

Also you can try this: grab the 0.10.*, the 0.12 package and [this one](https://github.com/Lymphatus/caesium-clt/files/2345023/clt.zip). Keep the same caesiumclt.exe file but change the .dlls from different packages and see the result. I think there might be an issue with them.

I will setup another Windows machine to run in-deep testing according to your reports.

PS. Sorry for the lack of responses in the last few weeks, but I just started a new job and moved to another city so I'm pretty busy right now 😁

**Comment by shimizurei** [comment]
Congrats on the new job! I figured you were probably super busy, so no worries.

About this part:

> Also you can try this: grab the 0.10.*, the 0.12 package and this one. Keep the same caesiumclt.exe file but change the .dlls from different packages and see the result.

Should I be testing this with image sets that complete their run, or should I try it on the files that have been crashing the program? I had started with working images and I was just wondering if anything could be gleaned from non-crashes.

**Comment by Lymphatus** [comment]
I would do the set that crashes, then another that seems to work fine eventually.
