### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by pranshuthegamer** [Lymphatus/caesium-clt#47]
make doesnt do anything

**Comment by Skywig08** [comment]
Hello, I got the same problem, I cannot install caesium-clt.
Maybe the makefile is missing ?
Can you make a release for the v0.16.0 ? 
I need the -RS fix for windows

**Comment by Lymphatus** [comment]
Windows compilation is a bit tricky, I must admit.

You can try like this:

```
cd caesium-clt
mkdir build
cd build
cmake.exe -DCMAKE_BUILD_TYPE=Release -DLIBCAESIUM_PATH=path\to\libcaesium -G "CodeBlocks - MinGW Makefiles" ..
cmake.exe --build . --target caesiumclt
```
This works on my machine with mingw installed on my PATH.

Also I'm attaching a compiled version. This is straight out of my working machine and not really tested, but SHOULD work.

[caesiumclt.zip](https://github.com/Lymphatus/caesium-clt/files/8235210/caesiumclt.zip)

**Comment by Skywig08** [comment]
Thanks, your compiled version worked, I suggest you add it to https://github.com/Lymphatus/caesium-clt/releases because it is way easier for Windows user and also maybe I use it wrong, but I had to run the CLT on my external drive to be able to compress photo on it, otherwise I got "command line JPEG compression error: The system cannot find the path specified. (os error 3)"
